spring.application.name=AutoService API
spring.datasource.url=jdbc:postgresql://localhost:5432/autoservice
spring.datasource.username=dbaauto
spring.datasource.password=Inf@2025
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect